= Email Encryption

For this lab, you will use public key encryption to send and receive encrypted emails.
You will receive full credit after you send me your public key, receive and decrypt my reply, and respond.
To give me time to respond, your first message to me must be sent by 8am on the day the assignment is due.
I will reply, and you must respond to my reply by the due date and time.

== Installing and configuring GPG and Thunderbird
There are some great free tools for enabling you to use PGP (Pretty Good Privacy) or GPG (Gnu Privacy Guard, a free, PGP-compatible encryption tool) to encrypt and sign all of your emails.
Here we'll use Thunderbird, an open source email client from Mozilla, the same team that makes Firefox.
Enigmail is a popular security plugin for Thunderbird that handles the GPG encryption.
Finally, you'll install a GPG application for your operating system.

. Go to https://www.mozilla.org/en-US/thunderbird/download to download and install the Mozilla Thunderbird email client
. Set up Thunderbird to use whatever email address you want to use for this lab. 
.. If you want to use Gmail, make sure that you have IMAP enabled. Do this by clicking the gear icon and selecting "Settings." Then go to the "Forwarding and POP/IMAP tab" and select "Enable IMAP."
.. If you're still having trouble getting it set up, there is a link to configuration instructions at the bottom of that page. Follow https://support.google.com/mail/troubleshooter/1668960?rd=1#ts=1665018,1665141[these instructions] to configure Gmail in Thunderbird.
. Install the GPG implementation for whichever platform you are using (Windows or Mac)
.. On Windows, go to http://www.gpg4win.org/ to download GPG (the Gnu Privacy Guard).
... For GPG4win, make sure you check the box to also install Kleopatra during the installation
.. On a Mac, go to http://gpgtools.org/ to download GPG Tools. After you install, it will ask if you wish to run GPGtools. Just close it, as you will generate our keys through Thunderbird.
. Once you have both GPG and Thunderbird installed, install the Enigmail add-on for Thunderbird (https://addons.mozilla.org/en-us/thunderbird/addon/enigmail/).
. Restart Thunderbird, and you will be prompted to configure Enigmail
. Follow the setup wizard prompts to generate your public and private keys
.. Select "Convenient auto encryption" when it is displayed. Also select to sign all of your messages by default.
.. Opt to "Create a new key pair" and follow the instructions on screen.
.. When prompted, you may create the revocation certificate if you wish. You won't need it for this lab, but if you want to continue using email encryption, it's a good idea.

== Exchanging public keys and sending emails

As you have learned, asymmetric (public key) encryption works because
you can share your public key with anyone, and they can use that public
key to encrypt a message meant just for you. In this section of the lab
we will exchange public keys so that we can send each other encrypted
messages

. Press the "Alt" key to bring up the menu in Thunderbird.
. Select "Enigmail" and then "Key Management"
. You will be presented with a list of keys installed on your computer (probably just your own)
. Install my public key
.. Download the appropriate public key file ([something].asc) from Blackboard.
.. In the "Key Management" window, select "File" -> "Import keys from file"
.. Right-click on the new key and select "Sign key". Signing keys is your way of indicating that you trust they key, and that you believe it truly belongs to me.
. Send me your own public key
.. Now that you have my public key, you can send me an encrypted message. Send me your own public key in an encrypted message using the following steps:
.. Right-click your own name in the "Key Management" window and select "Send Public Keys by Email"
.. Enter the email address provided by your instructor as the destination and "[Course number] - Encryption Lab" in the subject line.
.. In the body of the email. Tell me something interesting. Could be a fact, a story, what you did last summer, or what you are doing this summer. It doesn't matter, just say something that I can respond to.
.. Select the option to "Encrypt and sign the message text, but not the attachments." This will send your public key in plain text. Remember that that's okay; anybody can have your public key and it won't compromise your own security. So there's no harm in having your public key intercepted or shared.
. Respond to my message
.. To verify that you are able to both encrypt and decrypt a message, I will send you a response to your message from step 5. To complete the lab, you need to reply to my message. Make sure you keep my response in the body of your reply so I can verify that you received and decrypted it.

== If you'd rather

It is possible to send encrypted mail with Apple Mail, or through your webmail client like Gmail, Yahoo, etc. (http://lifehacker.com/how-to-encrypt-your-email-and-keep-your-conversations-p-1133495744[webmail instructions]).
If you would rather do that, you may, although you are responsible for troubleshooting any issues you come across.
The only true requirement for this lab is that you send your instructor an encrypted and signed message and respond to their encrypted reply.
Feel free to use Google to find out how to send GPG encrypted messages if you have a different preferred email client.
