= Data Communications Exercises
Ryan Schuetzler <ryan@schuetzler.net>
v0.1, 2016-08-23
:source-highlighter: pygments
:toc:
:doctype: book
:numbered:

[preface]
= About This Book

This book is a work in progress.  The ultimate goal is to provide a set of
computer exercises that will allow anyone who is interested to get hands-on
experience with networking using modern technologies

== Required Equipment

The only required equipment for the completion of these labs is a computer
capable of running multiple 64-bit virtual machines.  Most of the instructions
will assume you are using a Windows computer, but it is likely possible to
complete all the exercises with some modification on Linux or macOS.

Part of the goal of the book is to minimize software and hardware requirements
to make it possible to gain practical networking experience without specialized
networking hardware.  If you have access to enterprise grade switches, routers,
and firewalls that you can practice with and configure, then there are likely
other books that provide more instruction in that area.

