= Monitoring Traffic on a Switch

A monitoring port on a switch will mirror all traffic destined for specific ports. For example, a switch might have 24 ports. Port 1 might mirror traffice for ports 2 through 23. Every packet received in ports 2-23 will also be send to port 1. Monitoring ports can be used for network monitoring and traffic analysis.

== Prerequisites

* Access to a managed Cisco switch, such as the Cisco 2960

== Reload the Switch

* Connect to the switch through the console cable.
* Run the following commands. You may be prompted to enter a password.
+
```
Switch> enable
Switch# show flash
```
* If there is a `vlan.dat` file, delete it.
+
```
Switch# delete vlan.dat
```
* Erase the configuration and reload the switch.
+
```
Switch# erase startup-config
Switch# reload
```

== Before Monitoring

* Connect several computers to the switch.
    - Interface 1: Machine A: 192.168.2.5
	- Interface 2: Machine B: 192.168.2.10
	- Interface 3: Machine C: 192.168.2.15
	- Follow the above pattern until all computers are connected.
* Wait until the switch has completely rebooted before setting the IP addresses of the machines.
* Run the following command to set the IP addresses for each machine (substituting the appropriate IP address):
+
```
sudo ifconfig eth0 192.168.2.5
```
* Start Wireshark on all machines and capture the traffic in promisciousmode.
* Try to ping each machine. Note that you may need to disable firewalls and/or anti-virus for the pings to succeed. The pings should succeed.
* Look at the source and destination for the packets. Use this information to determine what network data each computer is receiving.

When Machine A pings Machine B, does Machine C see the traffic? Do not proceed until you can answer this question.

== Setup Monitoring

Use one of the computers to configure the switch. Run the following commands so that interface 3 receives a copy of all packets destine for interface the other interfaces on the 24 port switch.

```
Switch> en
Switch# config t
Switch(config)# no monitor session 1
Switch(config)# monitor session 1 source int f0/1-2,f0/4-24
Switch(config)# monitor session 1 destination int f0/3 encapsulation replicate
Switch(config)# end
```

Run the following command to review the monitoring setup.

```
Switch# show monitor session 1
```

== After Monitoring

* Capture the traffic on all computers connected to the switch in promiscious mode.
* Ping the various machines.

When Machine A pings Machine B, can Machine C see the traffic?

== Cleanup

* Use the instructions above to reset the switch configuration.
* Enable any firewall or anti-virus that may have been disabled.
