# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provision "shell", path: "install-py3.sh"
  config.vm.provision "shell", path: "create-venv.sh", privileged: false

end
