# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.provision "shell", inline: "echo Starting alice and bob"
  

  config.vm.define "alice" do |alice|
    alice.vm.box = "ubuntu/Trusty64"
    alice.vm.network "private_network", ip: "192.168.100.24"
    alice.vm.hostname = "alice"
    alice.vm.box_check_update = false
    alice.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
    end
  end
  
  config.vm.define "bob" do |bob|
    bob.vm.box = "ubuntu/Trusty64"
    bob.vm.network "private_network", ip: "192.168.100.25"
    bob.vm.box_check_update = false
    bob.vm.provision "shell", path: "webminrepo.sh"
    bob.vm.hostname = "bob"
  end

end
