= Physical Security Reviews

Physical security is often overlooked when performing a review of cyber defense. Attackers can gain access to critical systems and data if physical security is not robust. In the same way that a port scan might be used to discover weaknesses in a firewall configuration, a physical security review may uncover methods attackers could use to steal data or cause other harm to an organization.

== Prerequisites

* None

== Perform a Physical Security Review

It would be best to perform this type of review in a space with some known information technology infrastructure. Do not exceed your authorization. For example, if you find an unattended laptop and the screen is not locked, do not attempt to use it.

These items are not an exhaustive list of physical security controls but rather focus on controls that an attacker may be able to ascertain. Other controls (like regularly changing electronic lock codes, training employees, and maintaing written policies) must be considered when fully evaluating physical security.

=== Computer Equipment

- [ ] Unattended computers have locked screents
- [ ] Unattended computers are tethered
- [ ] Printers are tethered
- [ ] Privacy screens used for sensitive information
- [ ] Mobile phones are physically protected

=== Data

- [ ] Printed materials are properly filed
- [ ] Data is appropriately classified
- [ ] USB/external hard drives stored appropriately
- [ ] Shredders used for sensitive data

=== Access

- [ ] Method for identifying employees and guests present
- [ ] Office doors locked when empty

=== Information Technology Infrastructure

- [ ] Telecommunications closets are locked
- [ ] Physical access to wireless access points restricted

=== Surveillance

- [ ] Video camers in use
- [ ] Entry/exit doors monitored

=== External Barriers

- [ ] Bollards present
- [ ] Fencing appropriate
- [ ] Doors secure
- [ ] Windows sufficiently strong
- [ ] Locks are functioning

== Reflection

* What other physical security concerns did you find that were not on the list?
